import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useRef } from "react";
import { globalCss } from "../src/stitches.config";
import styles from "../styles/Home.module.css";

const Home: NextPage<{ theme: string }> = ({ theme }) => {
  const isDone = useRef(false);
  if (isDone.current === false) {
    isDone.current = true;
    globalCss({ html: { background: theme === "dark" ? "black" : "white" } })();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ color: theme === "dark" ? "white" : "black" }}>
        theme is {theme}
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const theme = ctx.req.cookies?.["theme"] ?? "";

  return {
    props: {
      theme,
    },
  };
};

export default Home;
